version: "3"

services:

  lambda-base:
    image: lambda-base:latest
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    env_file: docker.env
    tty: true
