networks:
  selenium-base-net:
    driver: bridge
    name: selenium-base-net
    external: true

services:

  standard-chrome:
    image: standard-chrome:latest
    build:
      context: ./dockerfile/
      dockerfile: standard-chrome.Dockerfile
    env_file: ../environments/standard-chrome.env
    networks:
      selenium-base-net:
        aliases:
          - standard-chrome

