networks:
  selenium-net:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}-net


services:

  node-chrome:
    image: node-chrome:latest
    build:
      context: ./dockerfile/
      dockerfile: node-chrome.Dockerfile
    env_file: ../environments/node.env
    networks:
      selenium-net:
        aliases:
          - node-chrome

  node-firefox:
    image: node-firefox:latest
    build:
      context: ./dockerfile/
      dockerfile: node-firefox.Dockerfile
    env_file: ../environments/node.env
    networks:
      selenium-net:
        aliases:
          - node-firefox

