networks:
  selenium-base-net:
    driver: bridge
    name: selenium-base-net
    external: true

services:

  node-chrome:
    image: node-chrome:latest
    build:
      context: ./dockerfile/
      dockerfile: node-chrome.Dockerfile
    env_file: ../environments/node.env
    networks:
      selenium-base-net:
        aliases:
          - node-chrome

  node-firefox:
    image: node-firefox:latest
    build:
      context: ./dockerfile/
      dockerfile: node-firefox.Dockerfile
    env_file: ../environments/node.env
    networks:
      selenium-base-net:
        aliases:
          - node-firefox

