#!/bin/bash -eu
cd $(dirname `realpath $0`);source .env

if "${GOLANG_BUILD:-true}"; then
    echo "Building.."
    docker-compose build ${COMPOSE_BUILD_OPTION} --build-arg ROOTDIR=${ROOTDIR} gorp-go
fi

docker-compose run --rm -u ${OWNER} gorp-go $(basename $0) ${@}
