version: '3.7'

services:

  gorp-go:
    container_name: gorp-go
    hostname: gorp-go
    image: gorp-go
    build:
      context: ${PWD}
      dockerfile: dockerfile/go.Dockerfile
      target: develop
    env_file:
      - ${PWD}/.env
    volumes:
      - ./api:/go/src

  gorp-node:
    container_name: gorp-node
    hostname: gorp-node
    image: node:12.16.0-alpine
    env_file: .env
    working_dir: /app
    volumes:
      - ./app:/app
