version: '3.7'

services:

  gorp-go:
    container_name: gorp-go
    hostname: gorp-go
    image: gorp-go
    env_file: .env
    build:
      context: ${PWD}
      dockerfile: dockerfile/go.Dockerfile
      target: develop
    volumes:
      - ./${APIDIR}:/${APIDIR}
