#!/bin/bash -eu
cd $(dirname `realpath $0`);source .env

if "${GOBUILD:-true}"; then
    echo "Building.."
    docker-compose build ${COMPOSE_BUILD_OPTION} gorp-postgres
fi

docker-compose up ${@} gorp-postgres
