version: '3.7'

services:

  webrtc-node:
    container_name: webrtc-node
    hostname: webrtc-node
    image: node:12.16.0-alpine
    working_dir: /app
    ports:
      - 3002:3002
    volumes:
      - ./app:/app

  webrtc-web:
    container_name: webrtc-web
    hostname: webrtc-web
    image: nginx:alpine
    working_dir: /web
    # ports:
    #   - 10080:80
    volumes:
      - ./web:/web
      - ./default.conf:/etc/nginx/conf.d/default.conf

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: 'webrtc.local -> http://webrtc-web:80'
      STAGE: local
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal
    depends_on:
      - webrtc-web
