version: "3"

services:

  selenium-hub:
    container_name: selenium-hub
    hostname: selenium-hub
    image: selenium/hub:3.141.59
    environment:
      - TZ=Asia/Tokyo
      - GRID_BROWSER_TIMEOUT=30
      - GRID_TIMEOUT=30
      - GRID_MAX_SESSION=10
    ports:
      - 4000:4444
