networks:
  selenium-net:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME}-net

services:
  fake:
    build:
      context: .
      dockerfile_inline: |
        FROM scratch
    command: fake
    networks:
      selenium-net:
