version: '2.3'

services:

  tbls:
    container_name: tbls
    hostname: tbls
    image: tbls:latest
    build:
      context: ${PWD}/
    user: "1000"
    environment:
      - "TZ=Asia/Tokyo"
    volumes_from:
      - tbls-contents
    depends_on:
      - tbls-db

  tbls-web:
    container_name: tbls-web
    hostname: tbls-web
    image: pagespeed/nginx-pagespeed:1.13.35.2
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - tbls-contents
    init: true

  tbls-db:
    container_name: tbls-db
    hostname: tbls-db
    image: mysql:5.7
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=tbls"
    volumes_from:
      - tbls-contents
    init: true

  tbls-contents:
    container_name: tbls-contents
    hostname: tbls-contents
    image: busybox
    volumes:
      - ${PWD}/db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
      - ${PWD}/db/etc/mysql/conf.d/:/etc/mysql/conf.d/
      - ${PWD}/work:/work

