version: '2.3'

services:

  laravel-web:
    container_name: laravel-web
    hostname: laravel-web
    image: nginx:stable-alpine
    networks:
      base-net:
        ipv4_address: 172.56.0.12
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/web:/web
    depends_on:
      - laravel-php
      - laravel-composer
      - laravel-node

  laravel-php:
    container_name: laravel-php
    hostname: laravel-php
    image: php:7.2.12-fpm-alpine
    networks:
      base-net:
        ipv4_address: 172.56.0.13
    volumes:
      - ${PWD}/web:/web

  laravel-composer:
    container_name: laravel-composer
    hostname: laravel-composer
    image: composer:1.7.3
    volumes:
      - ${PWD}/web:/app
    depends_on:
      - laravel-php

  laravel-node:
    container_name: laravel-node
    hostname: laravel-node
    image: node:10.13-alpine
    volumes:
      - ${PWD}/web:/web

