version: '2.3'

services:

  laravel-web:
    container_name: laravel-web
    hostname: laravel-web
    image: nginx:stable-alpine
    networks:
      base-net:
        ipv4_address: 172.56.0.12
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - laravel-contents
    depends_on:
      - laravel-php
      - laravel-composer
      - laravel-node

  laravel-php:
    container_name: laravel-php
    hostname: laravel-php
    image: php:7.2.12-fpm-alpine
    user: "1000:1000"
    networks:
      base-net:
        ipv4_address: 172.56.0.13
    volumes_from:
      - laravel-contents

  laravel-composer:
    container_name: laravel-composer
    hostname: laravel-composer
    image: composer:1.7.3
    user: "1000:1000"
    volumes:
        - ${PWD}/web:/app
    depends_on:
      - laravel-php

  laravel-node:
    container_name: laravel-node
    hostname: laravel-node
    image: node:10.13-alpine
    user: "1000:1000"
    volumes_from:
      - laravel-contents

  laravel-contents:
    container_name: laravel-contents
    hostname: laravel-contents
    image: busybox
    volumes:
        - ${PWD}/web:/web

