version: '2.3'

services:

  hexo-base:
    container_name: hexo-base
    hostname: hexo-base
    image: hexo-base
    build:
      context: ${PWD}/.
      target: development
      # target: release
    networks:
      base-net:
        ipv4_address: 172.56.0.22
    volumes:
      - ${PWD}/bootstrap.sh:/bootstrap.sh
      - ${PWD}/web:/web
